# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Digital Scholarship Services at Pitt
email: uls-dhsst@pitt.edu
description: > # this means to ignore newlines until "baseurl:"
  This is a blog for Digital Scholarship Services in the University Library
  System at the University of Pittsburgh.
baseurl: "" # the subpath of your site, e.g. /blog
url: "dssatpitt.github.io" # the base hostname & protocol for your site
twitter_username: dssatpitt
github_username:  dssatpitt

# Build settings
markdown: kramdown
